# Generated by Django 5.1.3 on 2024-11-23 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("stress", "Stress Management"),
                    ("sleep", "Sleep Improvement"),
                    ("mindfulness", "Mindfulness & Meditation"),
                    ("general", "General Mental Health"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
